### ISSUE TITLE
Make selector work for all seasons

### ISSUE THREAD

**Issue by aisflat439** [KenSparks-Dev/Sports-record-tracker-app#1]
Lebron has had a bunch of seaons, and as a fan I'd expect to see 2022-2023, not 2022

**Comment by aisflat439** [comment]
@KenSparks-Dev Hello this is a message

**Comment by KenSparks-Dev** [comment]
@aisflat439 PR Created: [All Seasons]( https://github.com/KenSparks-Dev/Sports-record-tracker-app/pull/8 )
